name: Release new package version

on:
  release:
    types: [ created ]

jobs:
  npm_package:
    name: Publish NPM package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@v3
        with:
          node-version: '22.16.0'
          registry-url: 'https://registry.npmjs.org'
          scope: '@igorppbr'
      - run: npm install
      - run: npm run build
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NODE_AUTH_TOKEN }}
          access: public
          registry: 'https://registry.npmjs.org'
